lservices:
  - type: web
    name: reseller-backend
    runtime: node
    plan: free
    region: oregon

    rootDir: backend

    buildCommand: pnpm install --frozen-lockfile
    startCommand: pnpm run start

    envVars:
      - key: NODE_ENV
        value: production
